### ISSUE TITLE
timeout waiting for "running"

### ISSUE THREAD

**Issue by davix** [josenk/vagrant-vmware-esxi#119]
```
$ vagrant up

Bringing machine 'default' up with 'vmware_esxi' provider...
==> default: Virtual Machine is already built.
==> default: The VM is already powered_on.
==> default: --- Waiting for state "running"

There was an error.
  Failed, timeout waiting for "running".
```
The vm is running on esxi server, but timeout from vagrant.

This is first time use so I haven't succeed.

vagrant 2.2.18
plugin 'vagrant-vmware-esxi (2.5.2)'!
exsi 7.0

**Comment by josenk** [comment]
Most likely you need open-vm-tools or vmware-tools installed.   See #4 of the Requirements.

**Comment by davix** [comment]
```
$ sudo apt-get install open-vm-tools
Reading package lists... Done
Building dependency tree
Reading state information... Done
open-vm-tools is already the newest version (2:11.2.5-2ubuntu1~ubuntu20.04.1).
0 upgraded, 0 newly installed, 0 to remove and 26 not upgraded.
```
installed now and issue same.

**Comment by jmcgnh** [comment]
In order for vagrant-vmware-esxi to see the new VM state change to "running", the *box* that is being installed must have been built with the open-vm-tools package installed and enabled as an automatically-started service. You haven't told us what box your Vagrantfile is calling for. If it's one of the "standard" boxes, we expect it will already have vm tools configured. If it's a box you built yourself or got from some other less experienced box builder, it's possible the vm tools were not built in and set up properly.

**Comment by davix** [comment]
here are the two boxes I tried:
 15   config.vm.box = 'hashicorp/precise64'
 15   config.vm.box = 'generic/ubuntu2004'
What should I check if the services are running in the VM?
Is there a way to tell if a box has the package included before the try?

**Comment by jmcgnh** [comment]
Hmm. I see it has been over a year since I last tried to do a vagrant-vmware-esxi install. But I still had everything in place so I tried it with the generic/ubuntu2004 box.

And it got past the "running" wait just fine, ESXi 6.7 reported that VM tools were running. (Yes, I see that you said you were at 7.0 but my old servers won't run that, so I can't help any further with debugging this issue.)(And my vagrant is version 2.2.6, so I'm way behind you on that front. As I said, it has been over a year....)

As for how to check if services are running, the web interface will show you the state of VM tools in the status summary for the VM. It might be helpful to know what you see there.

Learning what's in the box before trying it can be hard. Some box providers offer a glimpse into their box building environment; as you can see from this file - https://github.com/lavabit/robox/blob/master/scripts/ubuntu2004/vmware.sh - there are clues to hint that the VM tools are getting included. (roboxes and generic boxes were identical, last time I looked into the matter.)

It's possible you are doing everything right and the plugin may just need an update to handle a peculiarity of ESXi 7.0.

**Comment by josenk** [comment]
What should I check if the services are running in the VM?
  - First you need to check if it's installed.   Google `How to list installed packages on linux`.  Then you can google `how to check if a service is running on linux`
    - RHEL OS's `rpm -qa`
    - Deb type OS's `apt list`

Is there a way to tell if a box has the package included before the try?
  - If it's not documented.  Sorry, not really...

Some clarification about the "Running" state.
  - When the vm is "Running", all that really means is esxi (and the plugin) is able to figure out the IP address of the guest.   Keep in mind that --->> esxi does this task, not the plugin  <<---   Esxi does it using open-vm-tools or the vmware-tools packages installed on the guest.   If there is no open-vm-tools or vmware tools installed, then the plugin cannot get it either.
   - What is the side effect.
      - It takes a bit longer to deploy because the plugin gives up waiting for the IP address.
      - Things that depend on the IP address don't work.  `vagrant ssh` for example. 
      - It's not really possible to know if the OS is up or fully functional.

**Comment by davix** [comment]
> When the vm is "Running", all that really means is esxi (and the plugin) is able to figure out the IP address of the guest.

Oh, my network doesn't have DHCP service. Vagrant up locally doesn't need this. But in ESXI case, it's required, right?

**Comment by davix** [comment]
Update:
I manually set IP address for the VM.
Then run `vagrant up` again.
No more error and `vagrant ssh` works fine!

**Comment by josenk** [comment]
See item 6 under Requirements in the README... 
   Using fixed IP's instead of DHCP, would be a work-around.   Public boxes will never switch to "Running" state.

**Comment by davix** [comment]
@josenk, I do not understand what the meaning of "Public boxes" is.
Is there any case it can be running without IP?

BTW, will it be a better message to say "no IP" instead of "not running"?

**Comment by josenk** [comment]
If you create your own box, it would be a private box.  Since you are getting it from the public internet, it's public.

Yes, you can run without an ip.   For example, dos 6.2 or windows 3.1 works without an ip.   Those vms will never transition to Running state because there is no ip.

If you don't like it being called 'Running' you'll need to open an issue with Hashicorp/Vagrant...   I didn't create that definition.

**Comment by davix** [comment]
@josenk thanks for your reply.
