### ISSUE TITLE
vagrant ssh taking over 30 sec's to complete

### ISSUE THREAD

**Issue by mazmarz** [josenk/vagrant-vmware-esxi#16]
First of all, I want to say I have found this plugin extremely useful.  I am still attempting to understand everything but I am getting  a bit frustrated with the time it takes to ssh into my vagrant box. It works, but waiting 30 some seconds each time is getting a little annoying.  I have attached a typescript of the ssh debug from vagrant.  Let me know if you need any other info.
[vagrant_ssh.txt](https://github.com/josenk/vagrant-vmware-esxi/files/1738081/vagrant_ssh.txt)

**Comment by josenk** [comment]
Most likely it's a reverse DNS problem with the SSH daemon.

If you ssh directly to the guest (ssh vagrant@192.168.1.24), do you still have the same problem???  

 You may want to look at these:
https://superuser.com/questions/359344/ssh-is-slow-to-make-a-connection
https://askubuntu.com/questions/246323/why-does-sshs-password-prompt-take-so-long-to-appear
https://access.redhat.com/discussions/1173853

BTW:  "vagrant ssh"   is a built-in command to vagrant.   I only supply the username and IP to vagrant and it does the rest... 


Please test and let me know.

**Comment by mazmarz** [comment]
Hello Jonathan,

No, I know the issue you are referring too, but I don't this is the case
here:









*marco@dude SANDBOX]$ time /usr/bin/ssh vagrant@192.168.1.24
<vagrant@192.168.1.24> -p 22 -o LogLevel=FATAL -o Compression=yes -o
DSAAuthentication=yes -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o
UserKnownHostsFile=/dev/null -o
IdentityFile=/home/marco/Docker/K8s/SANDBOX/.vagrant/machines/K8master/vmware_esxi/private_keyLast
login: Mon Feb 19 20:27:06 2018 from 192.168.1.16[vagrant@k8master ~]$
logoutConnection to 192.168.1.24 closed.real    0m2.305suser
0m0.034ssys     0m0.042s[marco@dude SANDBOX]$ *


It seems to be this part that is running particularly slow:



*INFO runner: Running action: machine_action_read_state
#<Vagrant::Action::Builder:0x000000000312ad60>INFO warden: Calling IN
action:
#<VagrantPlugins::ESXi::Action::SetESXiPassword:0x0000000003a070c8>INFO
warden: Calling IN action:
#<VagrantPlugins::ESXi::Action::ReadSSHInfo:0x0000000003f62f40>*

And, as you have seen from the debug, it is doing this several times for
some reason.

regards,

Marco

On Mon, Feb 19, 2018 at 9:44 PM, Jonathan Senkerik <notifications@github.com

**Comment by mazmarz** [comment]
Hello Jonathan,

My issue is also with even "vagrant status".  To show you what is going on
I have included another typescript with timing this time too:
"scriptreplay --timing status_time.txt status_script.txt"
In the zip file is the Vagrantfile I'm using too.  Could be it also has
issues?

regards,

Marco

On Mon, Feb 19, 2018 at 9:44 PM, Jonathan Senkerik <notifications@github.com

**Comment by josenk** [comment]
I did some deeper digging...   My "vagrant ssh" command takes about 20 seconds to complete.    I always found the vagrant commands to be a bit slow, but just figured it's the way things works...

  Vagrant is calling some of my functions multiple times (as you've seen with the dump).  It's getting the guest's IP and checking it's status  (powered on/off, etc...).  On top of that, I must check esxi connectivity before doing anything...   So it add's up.   In a way it makes sense to always have the latest status of everything before attempting to do something.

OK, I decided to cache the guest's IP address if it's known.  The function will returned the known IP instead of running the commands to figure it out each time.   That dropped my "vagrant ssh" time from 20 seconds to around 7-8 seconds.    I believe that is a great improvement.

I've had many inquiries about changing static IP's, so I suspect a lot of people are finding a way (hack a way) to change the guest IP address.   So, I believe there is a slight risk that caching could give vagrant incorrect information.   I've added an option to disable the IP caching.   I'll finalize my testing and release an new version very soon...

**Comment by mazmarz** [comment]
Thanks for the effort! I unfortunately am traveling at the moment and won't be able to test it till next Monday or Tuesday at the latest.  It makes sense your explanation though all this checking vagrant is doing for a straight forward command such as ssh is still a bit puzzling to me.  

I have no issue with the nice solution you have come up with.  I presently let my dhcp server setup the IP addresses and then bind the MAC of the VM's to the IP on the same dhcp server if I need the IP to appear static.  So this change should only be positive for me.  Thanks!

**Comment by josenk** [comment]
Do you know how to update the plugins?   Just remove the old, then vagrant plugin install file.gem.   Could you give this a try and report back performance.

wget https://dc002.jintegrate.co/73748439276449/vagrant-vmware-esxi-2.0.4.gem

In your Vagrantfile, you can enable or disable the cache.
    esxi.local_use_ip_cache = 'True'

**Comment by mazmarz** [comment]
I will get back to you as soon as I get back and am able to test it.  Thanks!

**Comment by mazmarz** [comment]
OK, I can confirm that with caching ssh is now reasonable.  Around 8 seconds as you mentioned.  vagrant status is taking 18 seconds, however, but considering this is not a command I use that often I can deal with it.  Thanks again for the modification.

**Comment by josenk** [comment]
Fixed in V2.0.5.  BTW:  I found a few other places to save some time...  So it could be a bit better.

**Comment by mazmarz** [comment]
V2.0.5 is faster indeed than even the first fix.  Nice job.
