### ISSUE TITLE
Assign IP to Management Interface and Username/Password Setting

### ISSUE THREAD

**Issue by mingchen-chung** [josenk/vagrant-vmware-esxi#22]
Hi,

Thanks for this powerful plugin.
But, there are some problems for my usage (my Box is "generic/centos6)":

1. according to the readme, it seems I cannot assign IP to management interface. For management-wise and automation purpose, I prefer to give a static IP to my provisioned VM. Is there any suggestion to achieve this goal simply via Vagrant?

2. I try to set username/password to my VM via config.ssh.username and config.ssh.password, but it doesn't work. I cannot login via "vagrant ssh". The error message is as following:
"==> default: The machine you're attempting to SSH into is configured to use
==> default: password-based authentication. Vagrant can't script entering the
==> default: password for you. If you're prompted for a password, please enter
==> default: the same password you have configured in the Vagrantfile.".

I cannot login via console as well. Do I misconfigure my Vagrantfile?

Thanks in advance for your time, and look forward to your reply.

Ming-Chen

**Comment by josenk** [comment]
1)  Sorry, there is no easy way to set a fixed IP for the primary (first) network interface.   Vagrant doesn't allow it.  (This is a Vagrant issue, not a plugin/provider issue)


   2) config.ssh.username and config.ssh.password are used to SPECIFY an existing username and password to login.   These two options will NOT create the user for you.  That user must already exist in the box.  (This is also a Vagrant issue, not a plugin/provider issue)

  In the documentation 'By default this is "vagrant", since that is what most public boxes are made as.'
      https://www.vagrantup.com/docs/vagrantfile/ssh_settings.html

**Comment by josenk** [comment]
I updated the wiki to give you some hints on how to set a static IP on the mgmt interface.

https://github.com/josenk/vagrant-vmware-esxi/wiki/How-to-configure-a-static-IP-on-the-primary-interface.
