### ISSUE TITLE
Assign static IP

### ISSUE THREAD

**Issue by tenderitaf** [josenk/vagrant-vmware-esxi#31]
Hi,

How one can assign a static IP in a multi interface VM.

Regards

**Comment by josenk** [comment]
# Primary interface: 
    https://github.com/josenk/vagrant-vmware-esxi/wiki/How-to-configure-a-static-IP-on-the-primary-interface.

# Interface 2-4:
https://www.vagrantup.com/docs/networking/
   and 
https://github.com/josenk/vagrant-vmware-esxi/wiki/Vagrantfile-examle:-Single-Machine,-fully-documented.
```
  #  Vagrant can set a static IP for the additional network interfaces.  Use
  #  public_network or private_network to manually set a static IP and
  #  netmask.  ESXi doesn't use the concept of public or private networks so
  #  both are valid here.   'bridge' will be ignored.  Netmask is optional if
  #  you are using standard Class A/B/C networks. The primary network
  #  interface is considered the management interface and cannot be changed,
  #  so you can specify 3 entries here!
  #    *** Invalid settings could cause 'vagrant up' to fail ***
  #config.vm.network 'private_network', ip: '192.168.10.170', netmask: '255.255.255.0'
  #config.vm.network 'private_network', ip: '192.168.11.170'
  #config.vm.network 'public_network', ip: '192.168.12.170'
```

**Comment by tenderitaf** [comment]
Hi,
I have tried  already (copied literally the snippet above )
`config.vm.network 'private_network'`

But it doesn't assign any ip address. I'm deploying an ubuntu machine on ESXI 6.0 vagrant version 2.0.3.

Regards

**Comment by josenk** [comment]
Did you set your Virtual Networks???       

```
    #  HIGHLY RECOMMENDED!  Virtual Network
    #    You should specify a Virtual Network!  If it's not specified, the
    #    default is to use the first found.  You can specify up to 4 virtual
    #    networks using an array format.  Note that Vagrant only looks at the
    #    first interface for a valid IP address.  BTW: This does not configure
    #    IP addresses.  This specifies which 'ESXi virtual network' is used for
    #    each network interface in your VM.  For most OS's DHCP is the default,
    #    so, you will need a DHCP server for each virtual network.  To set a
    #    static IP, see above 'config.vm.network'.
    #esxi.esxi_virtual_network = ['vmnet1','vmnet2','vmnet3','vmnet4']
```

BTW:  How about some logs or some type of output from the plugin???   Just saying 'it doesn't work' doesn't give me much to work with.

**Comment by TheNotary** [comment]
Amazing work on this plugin, btw!  I was about to give up on a hobby project of mine but now I don't have to!!!

I was hung up on this issue about static IP addressing too.  I set my router to serve static routers to their macs which fixed the issue in the moment, but wanted to figure out how to do it elegantly all in my code.  

With these settings of just 'VM Network', I get an error

```
(Vagrantfile)
esxi.esxi_virtual_network = ['VM Network']

(console output)
$  vagrant up
.
storage-host-vm: --- WARNING         : esxi_virtual_network[1] not found, using VM Network
.
```

I think that error went away when I specified things like this:
```
esxi.esxi_virtual_network = ['VM Network', 'VM Network']
```

But that doesn't seem 100% correct to me (hopefully it's related to the solution).  


Anyway, I can recreate this problem by removing the static host on my router and change the IP address of say ubuntu-vm.  The bootup sequence looks promising:

```
$ vagrant up ubuntu
.
==> jenkins-vm: --- Configuring     : 192.168.1.126/255.255.255.0 on VM Network
==> jenkins-vm: An error occurred. The error will be shown after all tasks complete.
An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An error occurred while executing the action on the 'jenkins-vm'
machine. Please handle this error then try again:

Guest-specific operations were attempted on a machine that is not
ready for guest communication. This should not happen and a bug
should be reported.
.
```

So it indicates to me that it's configured to do it's static IP assignment, and shows a couple errors (possibly related?) and ultimately seems to go with the DHCP suggested IP address, as that I can still ping it's old IP and see that the box is there, and not at the newly changed ip of `192.168.1.126`.  

I'm not actually famaliar enough with the code-base yet to understand what happens after the [set network ip](https://github.com/josenk/vagrant-vmware-esxi/blob/8bd020dd8aeb1a07677587dbd17abfca5c747ccc/lib/vagrant-vmware-esxi/action/set_network_ip.rb#L115-L116) phase of the process.  Then again, there could be something messed up with my home networking that's interfering with stuff and isn't really a high priority since IP addresses shouldn't define your system, rather hostnames and other service discovery methods should be applied in the first place =/

**Comment by TheNotary** [comment]
Oh, here's a snippet of my Vagrant file in case it helps anyone:  https://gist.github.com/TheNotary/df4fb4dc012640ee47700ae904697e29

**Comment by josenk** [comment]
1) OK, first thing...  This message below:  Is not an Error.   It's a Warning.  :-)
```
storage-host-vm: --- WARNING         : esxi_virtual_network[1] not found, using VM Network
```
The reason why it's a WARNING is because you specified a static IP for the SECOND interface [index 1], but did not specify a virtual network, so the plugin choose the first found.  (Which is 'VM Network').

The WARNING went away after you modified esxi.esxi_virtual_network = ['VM Network', 'VM Network'] because you specified which Virtual Network to use for the second interface. 

This is all by design. If you specify a static IP address, but didn't specify enough Virtual Networks, the plugin to create it for you instead of error'ing out.

2) I'm not really sure if you're trying to set a static IP on the primary or secondary interface???  Vagrant does the IP address assignment on the VM, not my plugin.  It's very specific that I just send IP/Netmask/HW information for the second (or greater) interfaces.   I cannot send IP address information for the primary.  So that is why I cannot set an IP for the primary interface.   However, there are work-arounds.  I wrote a wiki article about setting at static IP on the primary interface.
>>https://github.com/josenk/vagrant-vmware-esxi/wiki/How-to-configure-a-static-IP-on-the-primary-interface

3) It's not clear why you get the error "Guest-specific operations were attempted on a machine...."???  Does it happen every time?   It could be caused by "node_config.vm.hostname = vm[:name]".   Try removing that line to see if it works better.   Again, Vagrant does the hostname assignment.   Make sure you have the most recent version of Vagrant.   I've seen that error many times in my testing, especially when trying to set the hostname and especially old versions of Vagrant.
