### ISSUE TITLE
Exit code is 0 on failure

### ISSUE THREAD

**Issue by ilpianista** [josenk/vagrant-vmware-esxi#53]
`vagrant up` failed with the timeout error:

    Failed, timeout waiting for "running"

But, surprisingly, the exit code is `0` when this happen. Shouldn't it be `1` (or something else)?

**Comment by josenk** [comment]
Good question.

   This is a common dilemma for all automation tools...    The tools worked exactly as expected, but the build may not be as expected.   So, do you exit success or failed??

    The reason why this may-not be considered an error...   If you purposely wanted to build a system that doesn't have or doesn't support vmware tools installed.  For example, If installing DOS or SCO Unix system it will never reach a "running" state.   Vagrant and the esxi plugin was actually successful with the build. 

   However, I agree with you that it should exit as failed because I believe the general usage of Vagrant and the esxi plugin will be with systems that DO support vmware tools.

**Comment by josenk** [comment]
Fixed in v2.4.0.  https://github.com/josenk/vagrant-vmware-esxi/releases/tag/v2.4.0
